jwt:
  secretKey: qwertyuioplkjhgfdsazxcvbnmsasasafsfmefsangsfwsmfweqnfmsadsafmsaf


spring:
  application:
    name: Week3-for-APIGateway-Microservice

  # api gateway configuration
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Week3-for-Order-Service-Microservice
          uri: lb://WEEK3-FOR-ORDER-SERVICE-MICROSERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2              # skip /api/v1/
            - name: LoggingOrdersFilter
            - name: Authentication       # if we flow convention of naming filter with suffix "GatewayFilterFactory", then we dont have to give complete name
              args:
                enabled: true          # used to pass arguments through the config class in the filter
#            # Filter of authorization for checking roles
#            - name: Authorization
#              args:
#                allowedRoles: ADMIN, SUPER_ADMIN
            # /api/v1/ will be handled by Spring Cloud Gateway(load balancer)
            # /orders/core will be handled by corresponding microservice
            # RedirectTo = 302, http://codingshuttle.com    // to redirect to another url
        - id: Week3-for-Inventory-Service-Microservice
          uri: lb://WEEK3-FOR-INVENTORY-SERVICE-MICROSERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2              # skip /api/v1/
            - AddRequestHeader=x-custom-header, Shivam
            - name: Authentication


